StoreApp.Web/Models/Cart.cs
using System;
using StoreApp.Data.Concrete;

namespace StoreApp.Web.Models;

public class Cart
{
    public List<CartItem> Items { get; set; } = new List<CartItem>();

    public virtual void AddItem(Product product, int quantity)
    {
        var item = Items.Where(p => p.Product.Id == product.Id).FirstOrDefault();

        if (item == null)
        {
            Items.Add(new CartItem { Product = product, Quantity = quantity });
        }
        else
        {
            item.Quantity += quantity;
        }
    }

    public virtual void RemoveItem(Product product)
    {
        Items.RemoveAll(i => i.Product.Id == product.Id);
    }

    public double CalculateTotal()
    {
        return Items.Sum(i => i.Product.Price * i.Quantity);
    }
    
    public virtual void Clear()
    {
        Items.Clear();
    }
}

public class CartItem
{
    public int CartItemId { get; set; }
    public Product Product { get; set; } = new();
    public int Quantity { get; set; }
}

StoreApp.Web/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Iyzipay;
using Iyzipay.Model;
using Iyzipay.Request;
using Microsoft.AspNetCore.Mvc;
using StoreApp.Data.Abstract;
using StoreApp.Data.Concrete;
using StoreApp.Web.Models;

namespace StoreApp.Web.Controllers
{
    public class OrderController : Controller
    {
        private Cart cart;
        private IOrderRepository _orderRepository;

        public OrderController(Cart cartService, IOrderRepository orderRepository)
        {
            cart = cartService;
            _orderRepository = orderRepository;
        }

        public IActionResult Checkout()
        {
            return View(new OrderModel() { Cart = cart });
        }
        [HttpPost]
        public async Task<IActionResult> Checkout(OrderModel model)
        {
            if (cart.Items.Count == 0)
            {
                ModelState.AddModelError("", "No product in your cart.");
            }
            if (ModelState.IsValid)
            {
                var order = new Order
                {
                    Name = model.Name,
                    Email = model.Email,
                    City = model.City,
                    Phone = model.Phone,
                    AdressLine = model.AdressLine,
                    OrderDate = DateTime.Now,
                    OrderItems = cart.Items.Select(i => new OrderItem
                    {
                        ProductId = i.Product.Id,
                        Price = (decimal)i.Product.Price,
                        Quantity = i.Quantity
                    }).ToList()
                };

                model.Cart = cart;
                var payment = await ProcessPayment(model);
                if (payment.Status == "success")
                {
                    _orderRepository.SaveOrder(order);
                    cart.Clear();
                    return RedirectToPage("/Complated", new {OrderId = order.Id});
                }
                
                 model.Cart = cart;
                return View(model);
                
            }
            else
            {
                model.Cart = cart;
                return View(model); 
            }
            
        }

        private async Task<Payment> ProcessPayment(OrderModel model)
        {
            Options options = new Options();
            options.ApiKey = "your api key";
            options.SecretKey = "your secret key";
            options.BaseUrl = "https://sandbox-api.iyzipay.com";
                    
            CreatePaymentRequest request = new CreatePaymentRequest();
            request.Locale = Locale.TR.ToString();
            request.ConversationId = new Random().Next(1111111111, 999999999).ToString();
            request.Price = model?.Cart?.CalculateTotal().ToString();
            request.PaidPrice = model?.Cart?.CalculateTotal().ToString();
            request.Currency = Currency.TRY.ToString();
            request.Installment = 1;
            request.BasketId = "B67832";
            request.PaymentChannel = PaymentChannel.WEB.ToString();
            request.PaymentGroup = PaymentGroup.PRODUCT.ToString();

            PaymentCard paymentCard = new PaymentCard();
            paymentCard.CardHolderName = model?.CartName;
            paymentCard.CardNumber = model?.CartNumber;
            paymentCard.ExpireMonth = model?.ExpirationMonth;
            paymentCard.ExpireYear = model?.ExpirationYear;
            paymentCard.Cvc = model?.Cvc;
            paymentCard.RegisterCard = 0;
            request.PaymentCard = paymentCard;

            Buyer buyer = new Buyer();
            buyer.Id = "BY789";
            buyer.Name = "John";
            buyer.Surname = "Doe";
            buyer.GsmNumber = "+905350000000";
            buyer.Email = "email@email.com";
            buyer.IdentityNumber = "74300864791";
            buyer.LastLoginDate = "2015-10-05 12:43:35";
            buyer.RegistrationDate = "2013-04-21 15:12:09";
            buyer.RegistrationAddress = "Nidakule Göztepe, Merdivenköy Mah. Bora Sok. No:1";
            buyer.Ip = "85.34.78.112";
            buyer.City = "Istanbul";
            buyer.Country = "Turkey";
            buyer.ZipCode = "34732";
            request.Buyer = buyer;

            Address shippingAddress = new Address();
            shippingAddress.ContactName = "Jane Doe";
            shippingAddress.City = "Istanbul";
            shippingAddress.Country = "Turkey";
            shippingAddress.Description = "Nidakule Göztepe, Merdivenköy Mah. Bora Sok. No:1";
            shippingAddress.ZipCode = "34742";
            request.ShippingAddress = shippingAddress;

            Address billingAddress = new Address();
            billingAddress.ContactName = "Jane Doe";
            billingAddress.City = "Istanbul";
            billingAddress.Country = "Turkey";
            billingAddress.Description = "Nidakule Göztepe, Merdivenköy Mah. Bora Sok. No:1";
            billingAddress.ZipCode = "34742";
            request.BillingAddress = billingAddress;

            foreach (var item in model?.Cart?.Items ?? Enumerable.Empty<CartItem>()) 
            {
            List<BasketItem> basketItems = new List<BasketItem>();
            BasketItem firstBasketItem = new BasketItem();
            firstBasketItem.Id = item.Product.Id.ToString();
            firstBasketItem.Name = item.Product.Name;
            firstBasketItem.Category1 = "Phone";
            firstBasketItem.Category2 = "Accessories";
            firstBasketItem.ItemType = BasketItemType.PHYSICAL.ToString();
            firstBasketItem.Price = item.Product.Price.ToString();
            basketItems.Add(firstBasketItem);
            }
            


            Payment payment = await Payment.Create(request, options);
                        return payment;
                    }
        }
    }

StoreApp.Web/Pages/Cart.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using StoreApp.Data.Abstract;
using StoreApp.Web.Helpers;
using StoreApp.Web.Models;

namespace StoreApp.Web.Pages
{
    public class CartModel : PageModel
    {
        private IStoreRepository _repository;

        public CartModel(IStoreRepository repository, Cart cartService)
        {
            _repository = repository;
            Cart = cartService;
        }
        public Cart? Cart { get; set; }
        public void OnGet()
        {
        }
        public IActionResult OnPost(int Id)
        {
            var product = _repository.Products.FirstOrDefault(i => i.Id == Id);

            if (product != null)
            {
                Cart?.AddItem(product, 1);
            }
            return RedirectToPage("/Cart");
        }

        public IActionResult OnPostRemove(int Id)
        {
            Cart?.RemoveItem(Cart.Items.First(p => p.Product.Id == Id).Product);

            return RedirectToPage("/Cart");
        }

    }
}

StoreApp.Web/Pages/Cart.cshtml
@page
@model StoreApp.Web.Pages.CartModel
@namespace StoreApp.Web.Pages
@using Microsoft.AspNetCore.Mvc.RazorPages
@using StoreApp.Web.Models
@using StoreApp.Web.Pages
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

<h2>Shopping Cart</h2>

 @if(Model?.Cart?.Items.Count() == 0)
    {
        <div class="alert alert-warning">Product Not Added</div>
    }
    else
    {
        <table class="table table-bordered table-striped">
                <thead>
                    <tr>
                        <th>Quantity</th>
                        <th>Item</th>
                        <th>Price</th>
                        <th>Total</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                
                @foreach(var item in (Model?.Cart?.Items ?? new List<CartItem>()))
                    {
                        <tr>
                                <td>@item.Quantity</td>
                                <td>@item.Product.Name</td>
                                <td>@item.Product.Price</td>
                                <td>
                                    @((item.Quantity * item.Product.Price).ToString()) ₺
                                </td>
                                <td>
                                    <form  method="post" asp-page-handler="Remove">
                                        <input type="hidden" name="Id" value="@item.Product.Id">
                                        <button type="submit"class="btn btn-sm btn-danger">Delete</button>
                                    </form>
                                </td>
                        </tr>
                    }
                    
                
                </tbody>
                <tfoot>
                    <tr>
                        <td colspan="3">Total : </td>
                        <td>
                            @Model?.Cart?.CalculateTotal() ₺
                        </td>
                    </tr>
                </tfoot>
        </table>
    }

<div>
    <a class="btn btn-primary" href="/">Continue Shopping</a>
    <a class="btn btn-success" asp-controller="Order" asp-action="Checkout">Complate Shopping</a>

</div>

StoreApp.Web/Pages/Complated.cshtml
@page 

<div class="text-center">
    <h2>Thank You For Order.</h2>
    <p>#@OrderId created number of order.</p>
    <p>Your order will be sent as soon as possible.</p>
    <a href="/" class="btn btn-primary">Home Page</a>
</div>

@functions{
    [BindProperty(SupportsGet = true)]
    
    public string? OrderId{get; set;}
}