StoreApp.Web/Components/CatagoriesListViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using StoreApp.Data.Abstract;
using StoreApp.Data.Concrete;
using StoreApp.Web.Models;

namespace StoreApp.Web.Components;

public class CatagoriesListViewComponent : ViewComponent
{
    private IStoreRepository _storeRepository;
    public CatagoriesListViewComponent(IStoreRepository storeRepository)
    {
        _storeRepository = storeRepository;
    }
    public IViewComponentResult Invoke()
    {
        ViewBag.SelectedCategory = RouteData?.Values["category"];
        return View(_storeRepository
            .Categories
            .Select(c => new CategoryViewModel
            {
                Id = c.Id,
                Name = c.Name,
                Url = c.Url
            } )
            .ToList());
    }
}

StoreApp.Web/Controllers/HomeController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using StoreApp.Data.Abstract;
using StoreApp.Data.Concrete;
using StoreApp.Web.Models;

namespace StoreApp.Web.Controllers;
  
public class HomeController : Controller
{
    public int pageSize = 3;
    private readonly IStoreRepository _storeRepository;
    private readonly IMapper _mapper;
    public HomeController(IStoreRepository storeRepository, IMapper mapper)
    {
        _storeRepository = storeRepository;
        _mapper = mapper;
    }
    public IActionResult Index(string category,int page = 1)
    {
        return View(new ProductListViewModel
        {
            Products = _storeRepository.GetProductsByCategory(category, page, pageSize)
                .Select(product => _mapper.Map<ProductViewModel>(product)),

            PageInfo = new PageInfo
            {
                ItemsPerPage = pageSize,
                CurrentPage = page,
                TotalItems = _storeRepository.GetProductCount(category)
            }
        });
    }
}

StoreApp.Web/Views/Home/Index.cshtml
@model StoreApp.Web.Models.ProductListViewModel
@using StoreApp.Web.Models
@using StoreApp.Web.TagHelpers
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@addTagHelper *, StoreApp.Web


<div class="row">
    <div class="col-md-3">
        <vc:catagories-list/>
    </div>
    <div class="col-md-9">

        @if(Model.Products.Count() == 0)
        {
            <p>No products available.</p>
        }
        
        @foreach(var p in Model.Products)
        {
            <div class="card card-outline-secondary mb-2 p-2">
                <div class="d-flex justify-content-between">
                    <div>
                        <h4>@p.Name</h4>
                        <p>@p.Description</p>
                    </div>
                    <div>
                        <span class="badge rounded-pill text-bg-success">@p.Price TL</span>
                    </div>
                </div>
                <form asp-page="/Cart" method="post">
                    <input type="hidden" asp-for="@p.Id" name="Id">
                    <button type="submit" class="btn btn-outline-success btn-sm pull-right" style="float: right;">Add to Cart</button>
                </form>
            </div>
        }
        @if(Model.PageInfo.TotalPages > 1)
        { 
            <div 
            page-model="@Model.PageInfo"
            page-action="Index"
            page-class="btn"
            page-class-link="btn-outline-dark"
            page-class-active="btn-dark"
            class="btn-group m-1"
            ></div>
        }
    </div>
</div>