StoreApp.Web/Components/CartSummaryViewComponent.cs
using System;
using Microsoft.AspNetCore.Mvc;
using StoreApp.Web.Models;


namespace StoreApp.Web.Components
{
    public class CartSummaryViewComponent : ViewComponent
    {
        private readonly Cart cart;
        public CartSummaryViewComponent(Cart cartService)
        {
            cart = cartService;
        }
        public IViewComponentResult Invoke()
        {
            return View(cart);
        }
    }
}

StoreApp.Web/Views/Shared/_Layout.cshtml
@using StoreApp.Web.Models
@using StoreApp.Web.TagHelpers
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@addTagHelper *, StoreApp.Web

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="/lib/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
    <title>Document</title>
</head>
<body>

    <partial  name="_Navbar"/>
    
    <div class="container my-3">
        @RenderBody()
    </div>

    <script src="/lib/bootstrap/js/bootstrap.min.js"></script>
    <script src="/lib/jquery/dist/jquery.min.js"></script>
    
</body>
</html>

StoreApp.Web/Views/Shared/_Navbar.cshtml
@using StoreApp.Web.Models
@using StoreApp.Web.TagHelpers
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@addTagHelper *, StoreApp.Web

<nav class="navbar navbar-expand-lg bg-dark border-bottom border-body" data-bs-theme="dark">
    <div class="container">
        <a href="/" class="navbar-brand">Store App</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#toggleContent">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="toggleContent">
            <ul class="navbar-nav me-auto">
                <li class="nav-item">
                    <a href="/" class="nav-link">Products</a>
                </li>
            </ul>
            <ul class="navbar-nav">
                <li class="nav-item">
                    <vc:cart-summary/>
                </li>
            </ul>

        </div>
    </div>
</nav>